language: bash

# for secret experimental features ;)
sudo: 9000

env:
  - VERSION=5.2
  - VERSION=5.1
  - VERSION=4.9
  - VERSION=4.8

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION"
  - image="gcc:$VERSION"

script:
  - docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
